/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include "JNIMath.h"
/* Header for class jnidemocalculadora_JNIMath */


/*
 * Class:     jnidemocalculadora_JNIMath
 * Method:    sumaNativa
 * Signature: (II)I
 * Detail: Metodo que se encarga de sumar dos numeros.
 */
JNIEXPORT jdouble JNICALL Java_jnidemocalculadora_JNIMath_sumaNativa
  (JNIEnv *env, jobject obj, jdouble num1, jdouble num2){
    return num1+num2;
}

/*
 * Class:     jnidemocalculadora_JNIMath
 * Method:    restaNativa
 * Signature: ()I
 * Detail: Metodo que se encarga de restar dos numeros.
 */
JNIEXPORT jdouble JNICALL Java_jnidemocalculadora_JNIMath_restaNativa
    (JNIEnv *env, jobject obj, jdouble num1, jdouble num2){
    return num1-num2;
}

/*
 * Class:     jnidemocalculadora_JNIMath
 * Method:    multiplicacionNativa
 * Signature: ()I
 * * Detail: Metodo que se encarga de multiplicar dos numeros.
 */
JNIEXPORT jdouble JNICALL Java_jnidemocalculadora_JNIMath_multiplicacionNativa
    (JNIEnv *env, jobject obj, jdouble num1, jdouble num2){
    return num1*num2;
}

/*
 * Class:     jnidemocalculadora_JNIMath
 * Method:    divisionNativa
 * Signature: ()I
 * Detail: Metodo que se encarga de dividir dos numeros.
 */
JNIEXPORT jdouble JNICALL Java_jnidemocalculadora_JNIMath_divisionNativa
    (JNIEnv *env, jobject obj, jdouble num1, jdouble num2){
    return num1/num2;
}
