/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnidemocalculadora_JNIMath */

#ifndef _Included_jnidemocalculadora_JNIMath
#define _Included_jnidemocalculadora_JNIMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnidemocalculadora_JNIMath
 * Method:    sumaNativa
 * Signature: (II)
 * Detail: Metodo suma que se implementara en C
 */
JNIEXPORT jdouble JNICALL Java_jnidemocalculadora_JNIMath_sumaNativa
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     jnidemocalculadora_JNIMath
 * Method:    restaNativa
 * Signature: ()I
 * Detail: Metodo resta que se implementara en C
 */
JNIEXPORT jdouble JNICALL Java_jnidemocalculadora_JNIMath_restaNativa
  (JNIEnv *, jobject, jdouble,jdouble);

/*
 * Class:     jnidemocalculadora_JNIMath
 * Method:    multiplicacionNativa
 * Signature: ()I
 * Detail: Metodo multiplicacion que se implementara en C
 */
JNIEXPORT jdouble JNICALL Java_jnidemocalculadora_JNIMath_multiplicacionNativa
  (JNIEnv *, jobject ,jdouble,jdouble);

/*
 * Class:     jnidemocalculadora_JNIMath
 * Method:    divisionNativa
 * Signature: ()I
 * Detail: Metodo division que se implementara en C
 */
JNIEXPORT jdouble JNICALL Java_jnidemocalculadora_JNIMath_divisionNativa
  (JNIEnv *, jobject , jdouble,jdouble);

#ifdef __cplusplus
}
#endif
#endif
